check RustNodeSyntax earlier.

diff --git a/.github/workflows/rust-astgen-ci.yml b/.github/workflows/rust-astgen-ci.yml
--- a/.github/workflows/rust-astgen-ci.yml
+++ b/.github/workflows/rust-astgen-ci.yml
@@ -78,6 +78,25 @@ jobs:
         with:
           workspaces: rust-astgen
 
+      - name: Build
+        run: cargo build --locked -p rust_ast_gen -p scala_bindings_gen
+
+      - name: Run tests
+        run: cargo test --locked -p scala_bindings_gen
+
+      - name: Regenerate Scala bindings
+        run: cargo run --locked -p scala_bindings_gen -- --include-date=false --output scala_tests/src/main/scala/io/joern/rust2cpg/parser/RustNodeSyntax.scala
+
+      - name: Check if there are changes
+        shell: bash
+        run: |
+          if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
+            echo "::error title=Repository modified by CI::Did you forget to commit regenerated files such as rust.ungram or RustNodeSyntax.scala?"
+            echo "Changes:"
+            git status --short
+            exit 1
+          fi
+
       - name: Set up Java
         uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
         with:
@@ -91,29 +110,10 @@ jobs:
       - name: Set up sbt
         uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
 
-      - name: Build
-        run: cargo build --locked -p rust_ast_gen -p scala_bindings_gen
-
-      - name: Run tests
-        run: cargo test --locked -p scala_bindings_gen
-
-      - name: Regenerate Scala bindings
-        run: cargo run --locked -p scala_bindings_gen -- --include-date=false --output scala_tests/src/main/scala/io/joern/rust2cpg/parser/RustNodeSyntax.scala
-
       - name: Run Scala tests
         working-directory: rust-astgen/scala_tests
         shell: bash
         run: sbt test
-
-      - name: Check if there are changes
-        shell: bash
-        run: |
-          if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
-            echo "::error title=Repository modified by CI::Did you forget to commit regenerated files such as rust.ungram or RustNodeSyntax.scala?"
-            echo "Changes:"
-            git status --short
-            exit 1
-          fi
 
   rust-ci-format:
     runs-on: ubuntu-latest
